apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.database.name }}
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
    # Start of the initContainer block to be removed
      initContainers:
      - name: init-mysql
        image: busybox
        command:
        - sh
        - -c
        - rm -rf /var/lib/mysql/*
        # - "[ -d /var/lib/mysql/mysql ] || rm -rf /var/lib/mysql/*"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        # - 
      containers:
      - name: {{ .Values.database.name }}
        image: mysql:5.7
        # image: mysql:5.8
        ports:
        - containerPort: {{ .Values.database.port }}
          name: {{ .Values.database.name }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: devops-db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: devops-db-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: devops-db-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: devops-db-secret
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.database.storage }}

