apiVersion: v1
kind: ServiceAccount
metadata:
  name: aks-admin
  namespace: kube-system

---
# Create ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aks-admin-binding
subjects:
- kind: ServiceAccount
  name: aks-admin
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
