apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  labels:
    app: {{ .Values.api.name }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
    spec:
      # imagePullSecrets:  
      # - name: {{ .Values.api.imagePullSecret }}
      containers:
      - name: {{ .Values.api.name }}
        image: {{ .Values.api.image }}:{{ .Values.api.tag }}
        ports:
        - containerPort: {{ .Values.api.port }}
        envFrom:
        - configMapRef:
            name: {{ .Values.api.configName }}
        - secretRef:
            name: {{ .Values.api.secretName }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.api.port }}
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.api.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
